### ISSUE TITLE
지역 DB 기준 문서화

### ISSUE THREAD

**Issue by yhjune** [CAPSTONE369/369_SERVER#10]
@sunnyineverywhere 이 배정해준 일

- [x] 지역 그룹 어떻게 나눌지 기준을 정해주세요
예) 서대문구 마포구 -> 그룹 1
이렇게 한곳에 묶일 지역 그룹들

- [x]  DB에 넣어주세요

일단은 한 그룹에 있는 지역끼리 게시글을 띄워줄 생각이었는데? 후에 개발하다 보면 방식이 바뀔 수는 있을 것 같음
사용자의 address를 기반으로 반경 5km 안쪽을 반환한다거나…

**Comment by yhjune** [comment]
//위도, 경도 -> 위치 : 역지오코딩

// 참고 블로그
https://papabee.tistory.com/153
https://velog.io/@sonagidev/Flutter-위치-정보를-받아서-시-구-를-화면에-띄우기

//api
https://developers.google.com/maps/documentation/geocoding/requests-reverse-geocoding?hl=ko
https://api.ncloud-docs.com/docs/ai-naver-mapsreversegeocoding-gc#

한국이니까 네이버 api 사용이 나을거 같음

**Comment by yhjune** [comment]
당근처럼 현재위치 ~ 가장 가까운 3군데 정도로 한정지어서 보여준다거나..
이러면 지금이랑 반대로 참조해서 Fk로 member랑 엮은 뒤에 불러오는 식으로 작동하거나 
member에 region을 아예 컬럼 추가해서 위치 뜬 거 저장하거나
다른 방식이 있나..?

전자가 나을 거 같은게 리전 테이블 아래 시 군 구 동 나눠서 저장하면 거래 불러올 때 jpa 돌리기 편할거 같은디

**Comment by yhjune** [comment]
현재 위치의 위도 경도 -> 지역 설정 -> 시 군 구 동 저장

**Comment by yhjune** [comment]
아 근디 가까운 3군데 보여주는건 또 구글 api 만 되네 네이버는 딱 그 지점만 보여주는 듯??

**Comment by yhjune** [comment]
다 틀렸음ㅋㅋㅋ 구글도 상세 주소 표기였음 가까운지역 보여주는게 아니라 
네이버 사용이 맞음

**Comment by yhjune** [comment]
네이버는 한국 법정동 표시가 되어서 좋음
구글은 플러스 코드라는게 있는데 위치 정보가 아주 세세하게 떠서 약속 장소 잡기에 좋은거 같음 배달 같은데 쓰이는 듯 (무료인게 제일 좋음)

**Comment by yhjune** [comment]
플러스코드 사이트
https://plus.codes/8Q7C5RW4+95

**Comment by yhjune** [comment]
지금 단계 베스트는 

1. 플러터에서 위/경도 받아옴 
2. 네이버 api 에서 region에 시/도, 군/구, 읍/면/동 리스폰스
3. rds에 저장
4. 지역 그룹은  같은 구끼리 묶는 거고 필요 시 군/구를 기준으로해서 jpa 반환이 나아보임

**Comment by yhjune** [comment]
그러면 공유 거래를 사용자한테 보여줄때는 같은 구인 걸 띄워주나...너무 먼가?
공유 거래는 동까지 하는게 나을 거 같은디...

**Comment by yhjune** [comment]
공유 거래는 동까지 하는게 나을거 같음

**Comment by yhjune** [comment]
네이버가 있으면 카카오도 있는디 
https://developers.kakao.com/docs/latest/ko/local/dev-guide#coord-to-district

**Comment by yhjune** [comment]
쓰읍 카카오 먼가..먼가,..? 리스폰스 값이 네이버가 우리가 원하는 형태임

카카오는 일케 뜨기 때문에 시랑 구를 파싱 함 더 해야댐 귀찮음
`{
      "region_type": "B",
      "address_name": "경기도 성남시 분당구 삼평동",
      "region_1depth_name": "경기도",
      "region_2depth_name": "성남시 분당구",
      "region_3depth_name": "삼평동",
      "region_4depth_name": "",
      "code": "4113510900",
      "x": 127.10459896729914,
      "y": 37.40269721785548
    },`

**Comment by sunnyineverywhere** [comment]
근데 여기서 문제: 플러터에서 위/경도 받아오는 **시점**의 기준은 어떻게 되는거? 처음 가입할때만?

**Comment by yhjune** [comment]
처음 가입 때 지역 설정하게 하면 그렇고, 설정 화면에서 수정가능하게 하려면 2번이지..?
